httpPort: 'APP_HTTP_PORT'
httpsPort: 'APP_HTTPS_PORT'
cookieSignature: 'APP_COOKIE_SIGNATURE'
secret: 'APP_SECRET'
db:
  name: 'DATABASE_NAME'
  host: 'DATABASE_HOST'
  port: 'DATABASE_PORT'
  username: 'DATABASE_USERNAME'
  password: 'DATABASE_PASSWORD'
  auth:
    name: 'AUTH_DATABASE_NAME'
    mechanism: 'AUTH_DATABASE_MECHANISM'
