httpPort: 3000
httpsPort: 3001
cookieSignature: generatedSignature
secret: generatedSecred
db:
  name: name
  host: localhost
  port: 27017
  username: username
  password: password
  auth:
    name: admin
    mechanism: SCRAM-SHA-1
